services:
    front:
        build: ./app/front
        volumes:
            - front:/front
        ports:
            - 3000:3000
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:3000/ || exit 1"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 30s
    back:
        build: ./app/back
        volumes:
            - back:/back
        ports:
            - 3001:3000
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:3000/ || exit 1"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 30s
    db:
        image: postgres:15
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=asdf
            - POSTGRES_DB=test

volumes:
    front:
        driver: local
        name: front
        driver_opts:
            type: none
            device: "./app/front"
            o: bind
    back:
        driver: local
        name: back
        driver_opts:
            type: none
            device: "./app/back"
            o: bind