services:
    app:
        build: ./app
        volumes:
            - app:/app
        ports:
            - 3000:3000
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:3000/ || exit 1"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 30s

    db:
        image: postgres:15
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=asdf
            - POSTGRES_DB=test

volumes:
    app:
        driver: local
        name: app
        driver_opts:
            type: none
            device: "./app/src"
            o: bind