services:
    front:
        build: ./app/front
        volumes:
            - front:/app
        ports:
            - 5000:3000
        networks:
            - front
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:3000/ || exit 1"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 30s
        depends_on:
            back:
                condition: service_healthy

    back:
        build: ./app/back
        volumes:
            - back:/app
        ports:
            - 3000:3000
        networks:
            - front
            - back
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:3000/ || exit 1"]
            interval: 2s
            timeout: 5s
            retries: 5
            start_period: 5s
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:15
        env_file:
            - ./app/back/src/.env
        networks:
            - back
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 5
            start_period: 5s

volumes:
    back:
        driver: local
        name: back
        driver_opts:
            type: none
            device: "./app/back/src"
            o: bind
    front:
        driver: local
        name: front
        driver_opts:
            type: none
            device: "./app/front/src"
            o: bind

networks:
    front:
    back:
