services:
    app:
        build: ./app
        volumes:
            - app:/app
        ports:
            - 3000:3000
        networks:
            - back
            - front
        healthcheck:
            test: ["CMD-SHELL", "curl http://127.0.0.1:3000/ || exit 1"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 30s
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:15
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=asdf
            - POSTGRES_DB=test
        networks:
            - back
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 5
            start_period: 5s

volumes:
    app:
        driver: local
        name: app
        driver_opts:
            type: none
            device: "./app/src"
            o: bind

networks:
    front:
    back:
